kind: Service
apiVersion: v1
metadata:
  name: crewmember-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: crewmember-api
    deployment: crewmember-api
