kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"redhat-airline-flight-api:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"redhat-airline-flight-api\")].image"}]
  name: flight-api
  labels:
    app: flight-api
    app.kubernetes.io/name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-api
      deployment: flight-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flight-api 
        deployment: flight-api
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: redhat-airline-flight-api
          image: quay.io/aibrahim/redhat-airline-flight-api:{{ .Values.version  }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: '8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

