kind: Service
apiVersion: v1
metadata:
  name: flight-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: flight-api
    deployment: flight-api
