kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"redhat-airline-ui:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"redhat-airline-ui\")].image"}]
  name: {{ .Values.appName }}
  labels:
    app:  {{ .Values.appName }}
    app.kubernetes.io/name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      deployment: {{ .Values.appName }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
        deployment: {{ .Values.appName }}
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: quay.io/aibrahim/{{ .Values.appName }}:{{ .Values.version }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef: 
                name: {{ .Values.appName  }}-conf
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

