kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ext-{{ .Values.appName }}
  {{- if eq .Values.engine "aks" }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  {{- end }}
spec:
  rules:
    - host: {{.Values.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 8080
