kind: Service
apiVersion: v1
metadata:
  name: cargo-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cargo-api
    deployment: cargo-api
