apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: airline-cache
  namespace: data-grid
spec:
  clusterName: infinispan
  name: bookings
  template: <infinispan><cache-container><distributed-cache name="offline-sessions" mode="SYNC" statistics="true" remote-timeout="17500">      <backups>
        <backup site="ARO" strategy="SYNC">
          <take-offline min-wait="120000"/>
        </backup>
      </backups><persistence><file-store/></persistence><state-transfer enabled="true" timeout="60000"/><transaction mode="NONE"/><locking striping="false" concurrency-level="1000" acquire-timeout="15000"/></distributed-cache></cache-container></infinispan>
